version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -D notes_db"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: