version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -D notes_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "postgresql+asyncpg://testuser:testpass@localhost:5432/notes_db"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 127.0.0.1 --port 8000 --reload
volumes:
  pgdata: